# Generated by Django 3.2.25 on 2024-03-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0030_auto_20240313_0943'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PotentialareaWindSTP2018Vreg',
            new_name='PotentialAreaWindSTP2018EG',
        ),
        migrations.DeleteModel(
            name='PotentialareaWindSTP2027Repowering',
        ),
        migrations.DeleteModel(
            name='PotentialareaWindSTP2027SearchAreaForestArea',
        ),
        migrations.DeleteModel(
            name='PotentialareaWindSTP2027SearchAreaOpenArea',
        ),
    ]
