# Generated by Django 3.2.25 on 2024-03-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0031_auto_20240314_0752'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PotentialareaWindSTP2027VR',
            new_name='PotentialAreaWindSTP2024VR',
        ),
    ]
