# Generated by Django 3.2.25 on 2024-03-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0033_auto_20240315_0930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PotentialareaPVRoadRailway',
        ),
    ]
