# Generated by Django 3.2.25 on 2024-03-18 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0035_potentialareapvroof'),
        ('map', '0043_auto_20240318_1629'),
    ]

    operations = [
    ]
