# Generated by Django 3.2.25 on 2024-03-28 10:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0044_merge_20240318_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionBoundaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'RegionBoundaries',
                'verbose_name_plural': 'RegionBoundaries',
            },
        ),
    ]
