# Generated by Django 4.2.11 on 2024-04-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0044_merge_20240318_1859"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreResults",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scenario", models.CharField(max_length=255)),
                ("parameters", models.JSONField()),
            ],
        ),
    ]
