# Generated by Django 4.2.11 on 2024-04-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0045_preresults"),
        ("map", "0045_regionboundaries"),
    ]

    operations = []
