# Generated by Django 4.2.11 on 2024-04-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0046_merge_0045_preresults_0045_regionboundaries"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PreResults",
        ),
    ]
