# Generated by Django 4.2.11 on 2024-05-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0049_alter_pvgroundareasapproved_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pvgroundareasapproved",
            options={"verbose_name": "Freiflächen-PV (genehmigt)", "verbose_name_plural": "Freiflächen-PV (genehmigt)"},
        ),
        migrations.AlterModelOptions(
            name="pvgroundareasoperating",
            options={
                "verbose_name": "Freiflächen-PV (in Betrieb)",
                "verbose_name_plural": "Freiflächen-PV (in Betrieb)",
            },
        ),
        migrations.AlterModelOptions(
            name="pvgroundareasplanned",
            options={"verbose_name": "Freiflächen-PV (geplant)", "verbose_name_plural": "Freiflächen-PV (geplant)"},
        ),
    ]
