# Generated by Django 4.2.11 on 2024-05-01 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0047_delete_preresults"),
        ("map", "0050_alter_pvgroundareasapproved_options_and_more"),
    ]

    operations = []
