# Generated by Django 4.2.11 on 2024-05-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0052_windturbine2planned_windturbine2operating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pvgroundareasapproved",
            name="capacity_net_inferred",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="pvgroundareasoperating",
            name="capacity_net_inferred",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="pvgroundareasplanned",
            name="capacity_net_inferred",
            field=models.BooleanField(null=True),
        ),
    ]
