# Generated by Django 4.2.16 on 2024-10-17 10:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0053_pvgroundareasapproved_capacity_net_inferred_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PVGroundCriteriaMerged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
