# Generated by Django 4.2.16 on 2024-11-22 13:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0054_pvgroundcriteriamerged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterfirstorder',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
