# Generated by Django 4.2.16 on 2024-11-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0057_potentialareawindstp2024vr_municipality_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='potentialareawindstp2024vr',
            options={'verbose_name': 'Vorranggebiet 1. Entwurf 2024', 'verbose_name_plural': 'Vorranggebiete 1. Entwurf 2024'},
        ),
    ]
