# Generated by Django 4.2.16 on 2024-11-26 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0058_alter_potentialareawindstp2024vr_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='potentialareawindstp2024vr',
            old_name='municipality_id',
            new_name='mun_id',
        ),
    ]
