# Generated by Django 4.2.16 on 2024-11-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0059_rename_municipality_id_potentialareawindstp2024vr_mun_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='potentialareawindstp2024vr',
            options={'verbose_name': 'Windvorranggebiet 1. Entwurf 2024', 'verbose_name_plural': 'Windvorranggebiete 1. Entwurf 2024'},
        ),
    ]
