# Generated by Django 4.2.16 on 2024-11-26 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0060_alter_potentialareawindstp2024vr_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='potentialareawindstp2018eg',
            options={'verbose_name': 'Windeignungsgebiet 2018', 'verbose_name_plural': 'Windeignungsgebiete 2018'},
        ),
        migrations.AddField(
            model_name='potentialareawindstp2018eg',
            name='mun_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='map.municipality'),
        ),
        migrations.AddField(
            model_name='potentialareawindstp2018eg',
            name='weg_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
