# Generated by Django 4.2.16 on 2024-11-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0061_alter_potentialareawindstp2018eg_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialareawindstp2018eg',
            name='weg_nr',
            field=models.IntegerField(null=True),
        ),
    ]
