repo_name: empowerplan/epp-app
repo_url: https://github.com/empowerplan/epp-app
site_name: EmPowerPlan Dokumentation
site_url: http://127.0.0.1:8000/

nav:
  - Start: index.md
  - Entwickler (en):
    - Setup: setup.md
    - Technologien: technology.md
    - Datenstruktur: data_structure.md
  - API:
    - App Configuration: api/apps.md
    - Calculations: api/calculations.md
    - Charts: api/charts.md
    - Choropleths: api/choropleths.md
    - Configuration: api/config.md
    - Datapackage: api/datapackage.md
    - Forms: api/forms.md
    - Hooks: api/hooks.md
    - Managers: api/managers.md
    - Map Configuration: api/map_config.md
    - Menu: api/menu.md
    - Migrations: api/migrations.md
    - Models: api/models.md
    - Popups: api/popups.md
    - Template Tags: api/templatetags.md
    - URLs: api/urls.md
    - Utils: api/utils.md
    - Views: api/views.md
    - Widgets: api/widgets.md

plugins:
  - search:
      lang:
        - en
        - de
  - gen-files:
      scripts:
        - docs/api_docs.py
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false

theme:
  name: material
  features:
    - navigation.footer
    - navigation.tracking
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - toc.follow
    - search.highlight
    - search.suggestions
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - docs/stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.smartsymbols:
      arrows: True
  - toc:
      permalink: "#"
  - admonition
  - pymdownx.details
  - pymdownx.superfences
