version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: empowerplan_production_django
    restart: unless-stopped
    networks:
      - empowerplan_network
      - caddy_network
    volumes:
      - ./empowerplan/data:/app/empowerplan/data
      - ./empowerplan/static/mvts:/app/staticfiles/mvts
    expose:
      - "5000"
    depends_on:
      - postgres
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: empowerplan_production_postgres
    command: postgres -N 500
    restart: always
    networks:
      - empowerplan_network
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: redis
    networks:
      empowerplan_network:

  celeryworker:
    <<: *django
    image: empowerplan_production_celeryworker
    command: /start-celeryworker

networks:
  empowerplan_network:
  caddy_network:
    external:
      name: docker_caddy_network
