version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: enershelf_production_django
    restart: unless-stopped
      networks:
        - enershelf_network
        - caddy_network
      volumes:
        - ./enershelf/data:/app/enershelf/data
        - ./enershelf/static/mvts:/app/staticfiles/mvts
      expose:
        - "5000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: enershelf_production_postgres
    command: postgres -N 500
    restart: always
      networks:
        - enershelf_network
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: redis:5.0
    restart: always
      networks:
        - enershelf_network

networks:
  enershelf_network:
  caddy_network:
    external:
      name: docker_caddy_network


