#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py compilemessages
python /app/manage.py collectstatic --noinput --ignore=mvts
python /app/manage.py compress --force
python /app/manage.py collectstatic --noinput --ignore=mvts
/venv/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --worker=4 --timeout=240 --chdir=/app
